name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          [
            { folder: "breft_editor", target: "breft" },
            { folder: "nand_dump", target: "nand" },
            { folder: "nandBinCheck", target: "nandBinCheck" },
            { folder: "nandExtract", target: "nandExtract" },
            { folder: "ohneschwanzenegger", target: "refleurii" },
            { folder: "punetwiin", target: "punetween" },
            { folder: "symbolizer", target: "symbolizer" },
          ]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          sudo add-apt-repository ppa:ubuntuhandbook1/ppa -y
          sudo apt install qt4-dev-tools libqt4-dev libqtcore4 libqtgui4 g++ -y

      - name: Compile
        run: |
          cd ${{ matrix.project.folder }}
          qmake -qt=qt4 ${{ matrix.project.target }}.pro
          make -f Makefile
  
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: dist
