name: WinBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: windows-latest
    strategy:
      matrix:
        project:
          [
            { folder: "breft_editor", target: "breft" },
            { folder: "nand_dump", target: "nand" },
            { folder: "nandBinCheck", target: "nandBinCheck" },
            { folder: "nandExtract", target: "nandExtract" },
            { folder: "ohneschwanzenegger", target: "refleurii" },
            { folder: "punetwiin", target: "punetween" },
            { folder: "symbolizer", target: "symbolizer" },
          ]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          choco install qt-sdk-windows-x86-msvc2010_opengl
          echo "QTDIR=C:\Qt\4.8.7" >> $GITHUB_ENV
          echo "QMAKESPEC=win32-msvc2010" >> $GITHUB_ENV
          echo "PATH=C:\Qt\4.8.7\bin;C:\Qt\4.8.7\lib;$PATH" >> $GITHUB_ENV

      - name: Compile
        run: |
          cd ${{ matrix.project.folder }}
          qmake ${{ matrix.project.target }}.pro
          nmake

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.0
        with:
          name: build-artifacts-${{ github.run_id }}-${{ github.run_number }}-${{ matrix.project.target }}
          path: |
            ${{ matrix.project.folder }}
