name: WinBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        project:
          [
            { folder: "breft_editor", target: "breft" },
            { folder: "nand_dump", target: "nand" },
            { folder: "nandBinCheck", target: "nandBinCheck" },
            { folder: "nandExtract", target: "nandExtract" },
            { folder: "ohneschwanzenegger", target: "refleurii" },
            { folder: "punetwiin", target: "punetween" },
            { folder: "symbolizer", target: "symbolizer" },
          ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download and install Qt4 on Windows
        run: |
          $qt4_url = "https://download.qt.io/archive/qt/4.8/4.8.7/qt-opensource-windows-x86-mingw482-4.8.7.exe"
          Invoke-WebRequest -Uri $qt4_url -OutFile qt4_installer.exe
          Start-Process -Wait -FilePath .\qt4_installer.exe -ArgumentList '/S'
          # Extract Qt4 binaries
          7z x -oQt4 -y qt4_installer.exe
          [System.Environment]::SetEnvironmentVariable('Path', "$($env:Path);C:\Qt4\bin", [System.EnvironmentVariableTarget]::Process)



      - name: Compile on Windows
        run: |
          cd ${{ matrix.project.folder }}
          C:\Qt4\bin\qmake -qt=qt4 ${{ matrix.project.target }}.pro
          nmake

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.0
        with:
          name: build-artifacts-${{ github.run_id }}-${{ github.run_number }}-${{ matrix.project.target }}
          path: |
            ${{ matrix.project.folder }}
