name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: windows-2019
    strategy:
      matrix:
        project:
          [
            { folder: "breft_editor", target: "breft" },
            { folder: "nand_dump", target: "nand" },
            { folder: "nandBinCheck", target: "nandBinCheck" },
            { folder: "nandExtract", target: "nandExtract" },
            { folder: "ohneschwanzenegger", target: "refleurii" },
            { folder: "punetwiin", target: "punetween" },
            { folder: "symbolizer", target: "symbolizer" },
          ]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '4.*.*'
          host: 'windows'
      - name: Setup MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1




      - name: Compile
        run: |
          cd ${{ matrix.project.folder }}
          qmake -qt=qt4 ${{ matrix.project.target }}.pro
          nmake 
