name: WinBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    strategy:
      matrix:
        project:
          [
            { folder: "breft_editor", target: "breft" },
            { folder: "nand_dump", target: "nand" },
            { folder: "nandBinCheck", target: "nandBinCheck" },
            { folder: "nandExtract", target: "nandExtract" },
            { folder: "ohneschwanzenegger", target: "refleurii" },
            { folder: "punetwiin", target: "punetween" },
            { folder: "symbolizer", target: "symbolizer" },
          ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download and extract Qt4
        run: |
          $url = 'https://download.qt.io/archive/qt/4.8/4.8.7/qt-opensource-windows-x86-mingw482-4.8.7.exe'
          Invoke-WebRequest -Uri $url -OutFile qt-installer.exe
          Start-Process -Wait -FilePath qt-opensource-windows-x86-mingw482-4.8.7.exe
          del qt-installer.exe

      - name: Set up Qt4 environment
        run: |
          $env:QTDIR = 'C:\Qt\4.8.7'
          $env:PATH = "C:\Qt\4.8.7\bin;$env:PATH"

      - name: Compile
        run: |
          cd ${{ matrix.project.folder }}
          qmake ${{ matrix.project.target }}.pro
          nmake

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.0
        with:
          name: build-artifacts-${{ github.run_id }}-${{ github.run_number }}-${{ matrix.project.target }}
          path: |
            ${{ matrix.project.folder }}
