name: WinBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: windows-latest
    strategy:
      matrix:
        project:
          [
            { folder: "breft_editor", target: "breft" },
            { folder: "nand_dump", target: "nand" },
            { folder: "nandBinCheck", target: "nandBinCheck" },
            { folder: "nandExtract", target: "nandExtract" },
            { folder: "ohneschwanzenegger", target: "refleurii" },
            { folder: "punetwiin", target: "punetween" },
            { folder: "symbolizer", target: "symbolizer" },
          ]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          choco install qt4-vs2010 -y

      - name: Compile
        run: |
          cd ${{ matrix.project.folder }}
          "C:\Qt\4.8.7\bin\qmake.exe" ${{ matrix.project.target }}.pro
          "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
          nmake
     
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.0
        with:
          name: build-artifacts-${{ github.run_id }}-${{ github.run_number }}-${{ matrix.project.target }}
          path: |
            ${{ matrix.project.folder }}
